application_id = GP4927
dev_team_lead = brian.jackson@xenial.com
exec_lead = 
security_champion = darius.remeika@xenial.com
observers = zoltan.boszormenyi@xenial.com, norbert.toth@xenial.com
prod_branch = master
dev_branch = develop
prod_urls = 
qa_urls = 
dev_urls = 
