/*
 * COPYRIGHT (C) 2005-2026 SICOM Systems Inc
 * 1684 S. Broad Street Suite 300
 * Lansdale, PA 19446
 * 215-489-2500, FAX: 215-489-2769
 */

#ifndef DETECTPOSHW_H
#define DETECTPOSHW_H

/*
 * The order of this list should not change, ever.
 * New entries must be added before SICOM_POSHW_N_IDS.
 * Only add "unsupported" in a comment on a line when
 * some POS hardware gets obsoleted.
 */
typedef enum {
	SICOM_POSHW_ID_UNKNOWN = -1,
	SICOM_POSHW_ID_SL18 = 0,
	SICOM_POSHW_ID_SL19,
	SICOM_POSHW_ID_SL20,
	SICOM_POSHW_ID_SL20P,
	SICOM_POSHW_ID_IBM500,
	SICOM_POSHW_ID_DLI8300,
	SICOM_POSHW_ID_MICROSWS4LX,
	SICOM_POSHW_ID_MICROSWS5,
	SICOM_POSHW_ID_MICROSWS5A,
	SICOM_POSHW_ID_MICROSPCWS2010,
	SICOM_POSHW_ID_LITERAY,
	SICOM_POSHW_ID_PTSP1000,
	SICOM_POSHW_ID_PTSP850,
	SICOM_POSHW_ID_GBOX,
	SICOM_POSHW_ID_ZBOXID41,
	SICOM_POSHW_ID_ZBOXID84,
	SICOM_POSHW_ID_ZBOXID86,
	SICOM_POSHW_ID_DELLBOX,
	SICOM_POSHW_ID_PICOBOX,
	SICOM_POSHW_ID_NCR_P1230,
	SICOM_POSHW_ID_SL20A,
	SICOM_POSHW_ID_FLTPOS335,
	SICOM_POSHW_ID_SL21 = SICOM_POSHW_ID_FLTPOS335,
	SICOM_POSHW_ID_FLTPOS335_CD2,
	SICOM_POSHW_ID_SL21_CD2 = SICOM_POSHW_ID_FLTPOS335_CD2,
	SICOM_POSHW_ID_LGMP500,
	SICOM_POSHW_ID_SL21B,
	SICOM_POSHW_ID_SL21B_CD2,
	SICOM_POSHW_ID_LGMP500BDBC,
	SICOM_POSHW_ID_LGNC2100,
	SICOM_POSHW_ID_DOP3040,
	SICOM_POSHW_ID_TOSH_4852E70,
	SICOM_POSHW_ID_CI325,
	SICOM_POSHW_ID_CI329,
	SICOM_POSHW_ID_NDIS163,
	SICOM_POSHW_ID_SLK27,
	SICOM_POSHW_ID_MP10,
	SICOM_POSHW_ID_RPI3BPLUS,
	SICOM_POSHW_ID_MINIX,
	SICOM_POSHW_ID_DT166,
	SICOM_POSHW_ID_VIRTUALBOX,
	SICOM_POSHW_ID_VIRTUALBOXSVGA = SICOM_POSHW_ID_VIRTUALBOX,
	SICOM_POSHW_ID_KVMQXL,
	SICOM_POSHW_ID_KVMVIRTIOGPU,
	SICOM_POSHW_ID_KVMVGA,
	SICOM_POSHW_ID_FLTK737,
	SICOM_POSHW_ID_XENIALDTC,
	SICOM_POSHW_ID_TDQUEST10,
	SICOM_POSHW_ID_XENIALKSCAPL,
	SICOM_POSHW_ID_XENIALXC23,
	SICOM_POSHW_ID_VMWARE,
	SICOM_POSHW_ID_MP10EL,
	SICOM_POSHW_ID_MP30 = SICOM_POSHW_ID_MP10EL,
	SICOM_POSHW_ID_VBOXVMSVGA,
	SICOM_POSHW_ID_ARK1221L,
	SICOM_POSHW_ID_GC26,
	SICOM_POSHW_N_IDS
} sicom_poshw_id_t;

/* Obsoleted functions returning 0/1 */
int detectposhw_is_SICOMsl18(void);
int detectposhw_is_SICOMsl19(void);
int detectposhw_is_SICOMsl20(void);
int detectposhw_is_SICOMsl20P(void);
int detectposhw_is_IBM500(void);
int detectposhw_is_DLI8300(void);
int detectposhw_is_MICROSsystem4LX(void);
int detectposhw_is_MICROSsystem5(void);
int detectposhw_is_MICROSsystem5A(void);
int detectposhw_is_MICROSpcws2010(void);
int detectposhw_is_LiteRay(void);
int detectposhw_is_PTsp1000(void);

/* New interfaces since 1.1.0 */
sicom_poshw_id_t detectposhw(void);
const char *detectposhw_get_hw_name(sicom_poshw_id_t hwid);
const char *detectposhw_get_version(void);

#endif /* DETECTPOSHW_H */
