/*
 * COPYRIGHT (C) 2015-2026 SICOM Systems Inc
 * 1684 S. Broad Street Suite 300
 * Lansdale, PA 19446
 * 215-489-2500, FAX: 215-489-2769
 */

#ifndef _CS5536_H_
#define _CS5536_H_

#include <stdint.h>

enum {
	DIVIL_GLD_MSR_CAP,
	DIVIL_GLD_MSR_CONFIG,
	DIVIL_GLD_MSR_SMI,
	DIVIL_GLD_MSR_ERROR,
	DIVIL_GLD_MSR_PM,
	DIVIL_GLD_MSR_DIAG,
	DIVIL_LBAR_IRQ,
	DIVIL_LBAR_KEL,
	DIVIL_LBAR_SMB,
	DIVIL_LBAR_GPIO,
	DIVIL_LBAR_MFGPT,
	DIVIL_LBAR_ACPI,
	DIVIL_LBAR_PMS,
	DIVIL_LBAR_FLSH0,
	DIVIL_LBAR_FLSH1,
	DIVIL_LBAR_FLSH2,
	DIVIL_LBAR_FLSH3,
	DIVIL_LEG_IO,
	DIVIL_BALL_OPTS,
	DIVIL_SOFT_IRQ,
	DIVIL_SOFT_RESET,
	NORF_CTL,
	NORTF_T01,
	NORTF_T23,
	NANDF_DATA,
	NANDF_CTL,
	NANDF_RSVD,
	DIVIL_AC_DMA,
	KELX_CTL,
	PIC_YSEL_LOW,
	PIC_YSEL_HIGH,
	PIC_ZSEL_LOW,
	PIC_ZSEL_HIGH,
	PIC_IRQM_PRIM,
	PIC_IRQM_LPC,
	PIC_XIRR_STS_LOW,
	PIC_XIRR_STS_HIGH,
	MFGPT_IRQ,
	MFGPT_NR,
	MFGPT_RSVD,
	MFGPT_SETUP,
	FLPY_3F2_SHDW,
	FLPY_3F7_SHDW,
	FLPY_372_SHDW,
	FLPY_377_SHDW,
	PIC_SHDW,
	PIT_SHDW,
	PIT_CNTRL,
	UART1_MOD,
	UART1_DONG,
	UART1_CONF,
	UART2_MOD,
	UART2_DONG,
	UART2_CONF,
	DMA_MAP,
	DMA_SHDW_CH0,
	DMA_SHDW_CH1,
	DMA_SHDW_CH2,
	DMA_SHDW_CH3,
	DMA_SHDW_CH4,
	DMA_SHDW_CH5,
	DMA_SHDW_CH6,
	DMA_SHDW_CH7,
	DMA_MSK_SHDW,
	LPC_EADDR,
	LPC_ESTAT,
	LPC_SIRQ,
	LPC_RSVD,
	PMC_LTMR,
	PMC_RSVD,
	RTC_RAM_LOCK,
	RTC_DOMA_OFFSET,
	RTC_MONA_OFFSET,
	RTC_CEN_OFFSET,
	GLCP_GLD_MSR_CAP,
	GLCP_GLD_MSR_CONFIG,
	GLCP_GLD_MSR_SMI,
	GLCP_GLD_MSR_ERROR,
	GLCP_GLD_MSR_PM,
	GLCP_GLD_MSR_DIAG,
	GLCP_CLK_DIS_DELAY,
	GLCP_PMCLKDISABLE,
	GLCP_GLB_PM,
	GLCP_DBGOUT,
	GLCP_DOWSER,
	GLCP_CLKOFF,
	GLCP_CLKACTIVE,
	GLCP_CLKDISABLE,
	GLCP_CLK4ACK,
	GLCP_SYS_RST,
	GLCP_DBGCLKCTL,
	GLCP_CHIP_REV_ID,
	LXMSR_MAX
};

typedef struct {
	uint32_t addr;
	char *name;
} lx_msr_t;

extern const lx_msr_t lx_msr[LXMSR_MAX];

enum {
	PIC_INT_SEL1,
	PIC_INT_SEL2,
	LXIO_MAX
};

typedef struct {
	uint16_t io;
	char *name;
} lx_io_t;

extern const lx_io_t lx_io[LXIO_MAX];

int cs5536(struct pci_dev *pdevs);

#endif /* _CS5536_H_ */
